##BASH SCRIPT TO INSTALL KDE DESKTOP EVIRONMENT ON ARCH LINUX OR ARCH BASED DISTROS, ENABLE sddm LOCK SCREEN MANAGER

##TO INSTALL KDE DESKTOP ENVIRONMENT 

	sudo pacman -Syu xorg plasma-meta sddm

##ONCE INSTALLATION IS FINISHED, WE HAVE TO ENABLE sddm LOCK SCREEN MANAGER SERVICE

##TO ENABLE TYPE sddm SERVICE 
	
	sudo systemctl enable sddm.service
 
